[package]
name = "iroh-rpc-client"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "RPC type client for iroh"

[dependencies]
async-stream = "0.3.3"
iroh-util = { path = "../iroh-util" }
iroh-rpc-types = { path = "../iroh-rpc-types", default-features = false }
cid = "0.8.0"
futures = "0.3.21"
tokio = { version = "1", features = ["sync"] }
anyhow = "1.0.57"
bytes = "1.1.0"
libp2p = { version = "0.50", default-features = false, features = ["gossipsub"] }
iroh-metrics = { path = "../iroh-metrics", default-features = false }
tracing = "0.1.34"
toml = "0.5.9"
serde = { version = "1.0", features = ["derive"] }
config = "0.13.1"
tarpc = { version = "0.30.0", features = ["serde1", "tokio1", "serde-transport", "serde-transport-bincode", "tcp"] }
async-trait = "0.1.56"
paste = "1.0.7"
bincode = "1.3.3"


[dev-dependencies]
tokio-stream = { version = "0.1.9", features = ["net"]}
iroh-rpc-types = { path = "../iroh-rpc-types", features = ["testing"] }

[features]
default = []
