[package]
name = "iroh-bitswap"
version = "0.1.0"
edition = "2021"
authors = ["David Craven <david@craven.ch>", "Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of the bitswap protocol"

[build-dependencies]
prost-build = "0.10"

[dependencies]
tokio = { version = "1.0", features = ["sync"] }
bytes = "1.1.0"
cid = "0.8.0"
futures = "0.3.5"
libp2p = { version = "0.45", default-features = false }
multihash = "0.16.0"
prost = "0.10"
thiserror = "1.0.20"
unsigned-varint = "0.7.0"
ahash = "0.7.6"
tracing = "0.1.34"
num_enum = "0.5.7"

[dev-dependencies]
criterion = "0.3.5"
env_logger = "0.9"
libp2p = { version = "0.45", features = ["yamux", "noise", "tcp-tokio"], default-features = false }
tokio = { version = "1.0", features = ["macros", "net", "rt"] }
tokio-util = { version = "0.7", features = ["compat"] }

[[bench]]
name = "message"
harness = false

[features]
