[bans]
multiple-versions = "allow"
deny = ["aws-lc", "aws-lc-rs", "aws-lc-sys", "native-tls", "openssl"]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",                        # BOSL license
    "ISC",
    "MIT",
    "Zlib",
    "MPL-2.0",                        # https://fossa.com/blog/open-source-software-licenses-101-mozilla-public-license-2-0/
    "Unicode-3.0",
    "Unlicense",                      # https://unlicense.org/
]


[advisories]
ignore = [
  "RUSTSEC-2024-0384", # unmaintained, no upgrade available
  "RUSTSEC-2024-0436", # paste
  "RUSTSEC-2023-0089", # unmainatined: postcard -> heapless -> atomic-polyfill
]
