[package]
name = "iroh-rpc-types"
version = "0.1.3"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "RPC type definitions for iroh"
rust-version = "1.65"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bytes = { version = "1.3.0", features = ["serde"] }
cid = { version = "0.9", features = ["serde-codec"] }
derive_more = "0.99.17"
futures = "0.3.24"
libp2p = { version = "0.50", default-features = false, features = ["serde"] }
quic-rpc = { version = "0.2.2", default-features = false }
serde = { version = "1" }
serde-error = "0.1.2"
serde_with = "2.1.0"
tokio = { version = "1", default-features = false }
