[package]
name = "iroh-rpc-types"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "RPC type definitions for iroh"


[dependencies]
async-trait = "0.1.56"
anyhow = "1.0.58"
serde_with = "2.0.0"
iroh-metrics = { path = "../iroh-metrics", default-features = false }
tokio = { version = "1", features = ["net", "sync"] }
tokio-stream = { version = "0.1.9", optional = true, features = ["net"] }
futures = "0.3.24"
tarpc = { version = "0.30.0", features = ["serde1", "tokio1", "serde-transport", "serde-transport-bincode", "tcp"] }
cid = { version = "0.8.6", features = ["serde-codec"] }
bytes = { version = "1.2.1", features = ["serde"] }
libp2p = { version = "0.50", default-features = false, features = ["serde"] }
serde = { version = "1.0.145", features = ["derive"] }
thiserror = "1.0.37"
paste = "1.0.9"
flume = "0.10.14"
bincode = "1.3.3"


[features]
default = []

# Builds and empty tonic server & client as well as associated protobufs
# that can be used for testing
testing = []
