[package]
name = "iroh-p2p"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of the p2p part of iroh"

[dependencies]
async-channel = "1.6.1"
asynchronous-codec = "0.6.0"
async-trait = "0.1"
anyhow = "1.0"
bytes = "1.1.0"
futures = "0.3.5"
futures-util = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.1.0"
cid = "0.8.0"
lazy_static = "1.4"
iroh-bitswap = { path = "../iroh-bitswap" }
iroh-rpc-types = { path = "../iroh-rpc-types" }
tokio = { version = "1.0", features = ["time", "sync", "macros"] }
ahash = "0.7.6"
tracing = "0.1.34"
clap = { version = "3.1.14", features = ["derive"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
iroh-rpc-client = { path = "../iroh-rpc-client" }
iroh-util = { path = "../iroh-util" }
tonic = "0.7.2"
tonic-health = "0.6.0"
iroh-metrics = { path = "../iroh-metrics" }
names = { version = "0.13.0", default-features = false }
git-version = "0.3.5"
prometheus-client = "0.16.0"
config = "0.13.1"
dirs = "4.0.0"
toml = "0.5.9"
 
[dependencies.libp2p]
version = "0.45"
default-features = false
features = [
  "gossipsub",
  "kad",
  "identify",
  "ping",
  "mdns",
  "noise",
  "yamux",
  "tcp-tokio",
  "dns-tokio",
  "mplex",
  "request-response",
  "websocket",
  "serde",
  "metrics",
] 

[dependencies.multihash]
version = "0.16"
default-features = false
features = ["std", "multihash-impl", "identity", "sha2"]

[dev-dependencies]
tokio = { version = "1.0.1" }
#car = { path = "../car" }

[features]
default = []

