[package]
name = "iroh-p2p"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of the p2p part of iroh"

[dependencies]
asynchronous-codec = "0.6.0"
async-trait = "0.1.56"
anyhow = "1.0"
bytes = "1.1.0"
futures = "0.3.21"
futures-util = "0.3.21"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.1.0"
cid = "0.8.0"
lazy_static = "1.4"
iroh-bitswap = { path = "../iroh-bitswap" }
iroh-rpc-types = { path = "../iroh-rpc-types", default-features = false }
iroh-rpc-client = { path = "../iroh-rpc-client", default-features = false }
tokio = { version = "1", features = ["time", "sync", "macros"] }
ahash = "0.7.6"
tracing = "0.1.34"
clap = { version = "3.1.14", features = ["derive"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
iroh-util = { path = "../iroh-util" }
iroh-metrics = { path = "../iroh-metrics", default-features = false, features = ["bitswap", "p2p"] }
names = { version = "0.14.0", default-features = false }
git-version = "0.3.5"
config = "0.13.1"
dirs = "4.0.0"
toml = "0.5.9"
zeroize = "1.4"
ssh-key = { version = "0.4.2", features = ["ed25519", "std", "rand_core"], default-features = false }
rand = "0.8.5"
async-stream = "0.3.3"
tempfile = "3.3.0"
caches = "0.2.2"
tokio-stream = "0.1"
 
[dependencies.libp2p]
version = "0.48"
default-features = false
features = [
  "gossipsub",
  "kad",
  "identify",
  "ping",
  "mdns",
  "noise",
  "yamux",
  "tcp-tokio",
  "dns-tokio",
  "mplex",
  "request-response",
  "websocket",
  "serde",
  "metrics",
  "relay",
  "dcutr",
  "autonat",
] 

[dependencies.multihash]
version = "0.16"
default-features = false
features = ["std", "multihash-impl", "identity", "sha2"]

[dev-dependencies]
# tokio = { version = "1" }
#car = { path = "../car" }

[features]
default = ["rpc-grpc", "rpc-mem"]
rpc-grpc = ["iroh-rpc-types/grpc", "iroh-rpc-client/grpc", "iroh-metrics/rpc-grpc"]
rpc-mem = ["iroh-rpc-types/mem", "iroh-rpc-client/mem"]

