[package]
name = "flatfs-store"
version = "0.1.2"
edition = "2021"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of FlatFS"
rust-version = "1.63"
publish = false

[dependencies]
anyhow = "1"
backoff = "0.4.0"
ignore = "0.4.18"

[dev-dependencies]
tempfile = "3.3.0"

[features]
default = []
