[package]
name = "iroh-rpc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "IPC/RPC client so different processes can communicate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkyv = { version = "0.7.37", features = ["std", "alloc", "validation"] }
libp2p = "0.44.0"
tokio = { version = "1.17.0", features = ["full"] }
futures = "0.3.21"
async-trait = "0.1.53"
bytecheck = "0.6.7"
smallvec = "1.8.0"
rand = "0.8.5"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
clap = "3.1.6"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.13"
serde_json = "1.0"
