[package]
name = "iroh-gateway"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "README.md"
description = "IPFS gateway"
repository = "https://github.com/dignifiedquire/iroh"

[dependencies]
iroh-rpc-client = { path = "../iroh-rpc-client", default-features = false }
iroh-rpc-types = { path = "../iroh-rpc-types", default-features = false }

cid = "0.8.6"

tokio = { version = "1", features = ["macros", "rt-multi-thread", "process"] }
axum = "0.5.1"
clap = { version = "3.1.14", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.78"
serde_qs = "0.10.1"
tower = { version = "0.4", features = ["util", "timeout", "load-shed", "limit"] }
mime_guess = "2.0.4"
iroh-metrics = { path = "../iroh-metrics", default-features = false, features = ["gateway"] }
tracing = "0.1.33"
names = { version = "0.14.0", default-features = false }
git-version = "0.3.5"
rand = "0.8.5"
tracing-opentelemetry = "0.18"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
time = "0.3.9"
headers = "0.3.7"
hyper = "0.14.19"
libp2p = { version = "0.49", default-features = false }
iroh-util = { path = "../iroh-util" }
anyhow = "1"
futures = "0.3.21"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
iroh-resolver = { path = "../iroh-resolver" }
tokio-util = { version = "0.7", features = ["io"] }
bytes = "1.1.0"
tower-layer = { version = "0.3" }
tower-http = { version = "0.3", features = ["trace", "compression-full"] }
http = "0.2"
async-recursion = "1.0.0"
handlebars = "4"
url = "2.2.2"
urlencoding = "2.1.0"
dirs = "4.0.0"
toml = "0.5.9"
http-serde = "1.1.0"
config = "0.13.1"
async-trait = "0.1.56"
sha2 = { version = "0.10", default-features = false }
reqwest = { version = "0.11.10", features = ["rustls-tls"], default-features = false}
hex-literal = "0.3.4"
hex = "0.4.3"
http-body = "0.4.5"

[dev-dependencies]
axum-macros = "0.2.0" # use #[axum_macros::debug_handler] for better error messages on handlers


[features]
default = ["rpc-grpc", "rpc-mem"]
rpc-grpc = ["iroh-rpc-types/grpc", "iroh-rpc-client/grpc", "iroh-metrics/rpc-grpc"]
rpc-mem = ["iroh-rpc-types/mem", "iroh-rpc-client/mem"]
