[package]
name = "iroh-gateway"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "README.md"
description = "IPFS gateway"
repository = "https://github.com/dignifiedquire/iroh"

[dependencies]
cid = "0.8.4"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "process"] }
axum = "0.5.1"
clap = { version = "3.1.14", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.78"
serde_qs = "0.9.2"
tower = { version = "0.4", features = ["util", "timeout", "load-shed", "limit"] }
mime_guess = "2.0.4"
iroh-metrics = { path = "../iroh-metrics" }
iroh-rpc-types = { path = "../iroh-rpc-types" }
tracing = "0.1.33"
tonic = "0.7.2"
tonic-health = "0.6.0"
names = { version = "0.13.0", default-features = false }
git-version = "0.3.5"
rand = "0.8.5"
tracing-opentelemetry = "0.17.2"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
time = "0.3.9"
headers = "0.3.7"
iroh-rpc-client = { path = "../iroh-rpc-client" }
hyper = "0.14.19"
libp2p = "0.46"
iroh-util = { path = "../iroh-util" }
anyhow = "1"
futures = "0.3.5"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
iroh-resolver = { path = "../iroh-resolver" }
prometheus-client = "0.16.0"
tokio-util = { version = "0.7.2", features = ["io"] }
bytes = "1.1.0"
tower-layer = { version = "0.3" }
tower-http = { version = "0.1", features = ["trace"] }
http = "0.2"
async-recursion = "1.0.0"
handlebars = "3"
url = "2.2.2"
urlencoding = "2.1.0"
dirs = "4.0.0"
toml = "0.5.9"
http-serde = "1.1.0"
config = "0.13.1"

[dev-dependencies]
axum-macros = "0.2.0" # use #[axum_macros::debug_handler] for better error messages on handlers
