[package]
name = "iroh-sync"
version = "0.5.1"
edition = "2021"
readme = "README.md"
description = "Iroh sync"
license = "MIT/Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh"

[dependencies]
anyhow = "1.0.71"
blake3 = { package = "iroh-blake3", version = "1.4.3"}
crossbeam = "0.8.2"
derive_more = { version = "1.0.0-beta.1", features = ["debug", "display", "from", "try_into"] }
ed25519-dalek = { version = "2.0.0-rc.2", features = ["serde", "rand_core"] }
flume = "0.10"
iroh-bytes = { version = "0.5.0", path = "../iroh-bytes" }
iroh-metrics = { version = "0.5.0", path = "../iroh-metrics", optional = true }
once_cell = "1.18.0"
postcard = { version = "1", default-features = false, features = ["alloc", "use-std", "experimental-derive"] }
rand = "0.8.5"
rand_core = "0.6.4"
serde = { version = "1.0.164", features = ["derive"] }
url = "2.4.0"
bytes = "1.4.0"
parking_lot = "0.12.1"
hex = "0.4"

# fs-store
redb = { version = "1.0.5", optional = true }
ouroboros = { version = "0.17", optional = true }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["sync", "macros"] }
tempfile = "3.4"

[features]
default = ["fs-store", "metrics"]
fs-store = ["redb", "ouroboros"]
metrics = ["iroh-metrics"]
