[package]
name = "iroh-willow"
version = "0.18.0"
edition = "2021"
readme = "README.md"
description = "willow protocol implementation for iroh"
license = "MIT/Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh"

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.75"

[lints]
workspace = true

[dependencies]
anyhow = "1"
bytes = { version = "1.4", features = ["serde"] }
curve25519-dalek = { version = "4.1.3", features = [ "digest", "rand_core", "serde", ] }
derive_more = { version = "1.0.0-beta.6", features = [ "debug", "deref", "display", "from", "try_into", "into", "as_ref", "try_from", ] }
ed25519-dalek = { version = "2.0.0", features = ["serde", "rand_core"] }
flume = "0.11"
futures-buffered = "0.2.6"
futures-concurrency = "7.6.0"
futures-lite = "2.3.0"
futures-util = "0.3.30"
genawaiter = "0.99.1"
hex = "0.4.3"
iroh-base = { version = "0.22.0", path = "../iroh-base" }
iroh-blobs = { version = "0.22.0", path = "../iroh-blobs" }
iroh-metrics = { version = "0.22.0", path = "../iroh-metrics", optional = true }
iroh-net = { version = "0.22.0", path = "../iroh-net" }
meadowcap = "0.1.0"
postcard = { version = "1", default-features = false, features = [ "alloc", "use-std", "experimental-derive", ] }
quinn = { package = "iroh-quinn", version = "0.10.5" }
rand = "0.8.5"
rand_core = "0.6.4"
redb = { version = "2.0.0" }
serde = { version = "1.0.164", features = ["derive"] }
sha2 = "0.10.8"
strum = { version = "0.26", features = ["derive"] }
syncify = "0.1.0"
thiserror = "1"
tokio = { version = "1", features = ["sync"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tokio-util = { version = "0.7", features = ["io-util", "io"] }
tracing = "0.1"
ufotofu = { version = "0.4.1", features = ["std"] }
willow-data-model = "0.1.0"
willow-encoding = "0.1.0"
zerocopy = { version = "0.8.0-alpha.9", features = ["derive"] }

[dev-dependencies]
iroh-test = { path = "../iroh-test" }
rand_chacha = "0.3.1"
tokio = { version = "1", features = ["sync", "macros"] }
proptest = "1.2.0"
tempfile = "3.4"
test-strategy = "0.3.1"
tracing-subscriber = "0.3.18"

[features]
default = ["metrics"]
metrics = ["iroh-metrics"]
