[[router]]
name = "dc"

[[router]]
name     = "lan-provider"
nat      = "destination-independent"

[[router]]
name     = "lan-fetcher"
nat      = "destination-independent"

[device.relay.eth0]
gateway = "dc"

[device.provider.eth0]
gateway = "lan-provider"

[device.fetcher.eth0]
gateway = "lan-fetcher"
