[package]
name = "iroh-unixfs"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Implementation of unixfs for iroh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
async-recursion.workspace = true
async-stream.workspace = true
async-trait.workspace = true
base64.workspace = true
bytes.workspace = true
cid.workspace = true
config.workspace = true
fastmurmur3.workspace = true
futures.workspace = true
iroh-metrics = { workspace = true, features = ["resolver", "gateway"] }
iroh-rpc-client.workspace = true
iroh-util.workspace = true
libipld.workspace = true
libp2p = { workspace = true, features = ["serde"] }
multihash.workspace = true
num_enum.workspace = true
once_cell.workspace = true
prost.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["rustls-tls", "json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true, features = ["io"] }
tracing.workspace = true
unsigned-varint.workspace = true

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
iroh-rpc-types.workspace = true
iroh-store.workspace = true
proptest.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread", "fs"] }

[build-dependencies]
prost-build.workspace = true
