[package]
name = "iroh-localops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.25", features = ["signal", "process"]}