[package]
name = "iroh-store"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of the storage part of iroh"

[dependencies]
rocksdb = "0.19.0"
anyhow = "1.0.57"
tokio = { version = "1", features = ["rt"] }
cid = "0.8.4"
rkyv = { version = "0.7.37", features = ["validation"] }
bytecheck = "0.6.7"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
clap = { version = "4.0.9", features = ["derive"] }
ctrlc = "3.2.2"
futures = "0.3.21"
tracing = "0.1.34"
iroh-rpc-types = { path = "../iroh-rpc-types", default-features = false }
iroh-rpc-client = { path = "../iroh-rpc-client", default-features = false }
iroh-util = { path = "../iroh-util" }
bytes = "1.1.0"
iroh-metrics = { path = "../iroh-metrics", default-features = false, features=["store"] }
tracing-opentelemetry = "0.18"
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
names = { version = "0.14.0", default-features = false }
git-version = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
config = "0.13.1"
async-trait = "0.1.56"
smallvec = { version = "1.10.0", features = ["write"] }
multihash = "0.16.3"
tarpc = { version = "0.30.0", features = ["serde1", "tokio1", "serde-transport", "serde-transport-bincode", "tcp"] }
paste = "1.0.9"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"] }
tempfile = "3.3.0"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
libipld = "0.14.0"

[features]
default = []

[[bench]]
name = "store"
harness = false

[[bench]]
name = "rpc"
harness = false
