[package]
name = "iroh-api"
version = "0.1.3"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "README.md"
description = "Rust API for Iroh"
rust-version = "1.63"
repository = "https://github.com/n0-computer/iroh"

[features]
testing = ["dep:mockall"]

[dependencies]
anyhow = "1"
async-stream = "0.3.3"
bytes = "1.1.0"
cid = "0.9"
config = "0.13.1"
futures = "0.3.21"
iroh-metrics = { version = "0.1.3", path = "../iroh-metrics", default-features = false, features = ["rpc-grpc"] }
iroh-resolver = { version = "0.1.3", path = "../iroh-resolver" }
iroh-rpc-client = { version = "0.1.3", path = "../iroh-rpc-client" }
iroh-rpc-types = { version = "0.1.3", path = "../iroh-rpc-types" }
iroh-util = { version = "0.1.3", path = "../iroh-util" }
libp2p = "0.50"
mockall = { version = "0.11.2", optional = true }
relative-path = "1.7.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1" }
tracing = "0.1.34"

[dev-dependencies]
tempfile = "3.3.0"
