[package]
name = "iroh-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "README.md"
description = "Rust API for Iroh"

[features]
testing = ["dep:mockall"]

[dependencies]
cid = "0.8.5"
config = "0.13.1"
iroh-metrics = { path = "../iroh-metrics", default-features = false, features = ["rpc-grpc"] }
iroh-resolver = { path = "../iroh-resolver" }
iroh-rpc-types = { path = "../iroh-rpc-types" }
iroh-rpc-client = { path = "../iroh-rpc-client" }
iroh-util = { path = "../iroh-util" }
anyhow = "1"
async-trait = "0.1.53"
tokio = { version = "1" }
bytes = "1.1.0"
libp2p = "0.49"
tracing = "0.1.34"
futures = "0.3.21"
async-stream = "0.3.3"
mockall = { version = "0.11.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
relative-path = "1.7.2"

[dev-dependencies]
tempdir = "0.3.7"