[package]
name = "portmapper"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "Portmapping utilities"
license = "MIT OR Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh"
keywords = ["portmapping", "pmp", "pcp", "upnp"]

[lints]
workspace = true

[dependencies]
anyhow = { version = "1" }
base64 = "0.22.1"
bytes = "1.7"
derive_more = { version = "1.0.0", features = ["debug", "display", "from", "try_into", "deref"] }
futures-lite = "2.3"
futures-util = "0.3.25"
igd-next = { version = "0.15.1", features = ["aio_tokio"] }
iroh-metrics = { version = "0.27.0", default-features = false }
libc = "0.2.139"
netwatch = { version = "0.1.0", path = "../netwatch" }
num_enum = "0.7"
rand = "0.8"
serde = { version = "1", features = ["derive", "rc"] }
smallvec = "1.11.1"
socket2 = "0.5.3"
thiserror = "1"
time = "0.3.20"
tokio = { version = "1", features = ["io-util", "macros", "sync", "rt", "net", "fs", "io-std", "signal", "process"] }
tokio-util = { version = "0.7.12", features = ["io-util", "io", "codec", "rt"] }
tracing = "0.1"
url = { version = "2.4", features = ["serde"] }

[dev-dependencies]
ntest = "0.9"
rand_chacha = "0.3.1"
tokio = { version = "1", features = ["io-util", "sync", "rt", "net", "fs", "macros", "time", "test-util"] }

[features]
default = ["metrics"]
metrics = ["iroh-metrics/metrics"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "iroh_docsrs"]
