[package]
name = "rocks-store"
version = "0.1.2"
edition = "2021"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of RocksDB based Store"
rust-version = "1.65"
publish = false

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
flatfs-store = { path = "../flatfs", optional = true }
rocksdb = "0.19.0"

[dev-dependencies]
flatfs-store = { path = "../flatfs" }
tempfile = "3.3.0"

[features]
importer = ["flatfs-store"]
