[package]
name = "rocks-store"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of RocksDB based Store"

[dependencies]
anyhow = "1"
flatfs-store = { path = "../flatfs", optional = true }
rocksdb = "0.19.0"

[dev-dependencies]
flatfs-store = { path = "../flatfs" }
tempfile = "3.3.0"


[features]
default = []
importer = ["flatfs-store"]


